<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6E83wHK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6E83wHK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6E83wHK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6E83wHK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6E83wHK\App_KernelDevDebugContainer([
    'container.build_hash' => '6E83wHK',
    'container.build_id' => '15bdab89',
    'container.build_time' => 1605564347,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6E83wHK');
